### ISSUE TITLE
Detect type of SPNEGO auth

### ISSUE THREAD

**Issue by Zubastic** [dotnet/Kerberos.NET#128]
I having a problem with win auth: I using windows computer with iis + windows auth. Computer not in domain, but I want to auth domain users. I generate keytab and load it:
```
KerberosValidator validator = new KerberosValidator(new KeyTable(File.ReadAllBytes(keytabPath)));
            try
            {
                var authenticator = new KerberosAuthenticator(validator) { UserNameFormat = UserNameFormat.DownLevelLogonName };

                    ClaimsIdentity identity = await authenticator.Authenticate(header);

                    context.User = new ClaimsPrincipal(identity);
                    logger.Trace("Successful logged in with kerberos: " + context.User.Identity.Name);
            }
            catch (Exception ex)
            {
                logger.LogException("Failed to auth with kerberos. Header: " + header, ex);
            }
```

It is working for domain users, but when I trying to auth from local machine with token: 
```
Negotiate oXcwdaADCgEBoloEWE5UTE1TU1AAAwAAAAAAAABYAAAAAAAAAFgAAAAAAAAAWAAAAAAAAABYAAAAAAAAAFgAAAAAAAAAWAAAABXCiOIKADk4AAAAD70taP1Ogwhx+AiPPOSLogKjEgQQAQAAAIkzoz+IJ/G0AAAAAA==
```

I got error:

```
2020-01-23 03:06:19.6758|ERROR|Test.Kerberos|Failed to auth with kerberos. Header: Negotiate oYIB7zCCAeugAwoBAaKCAc4EggHKTlRMTVNTUAADAAAAGAAYAIYAAAAcARwBngAAAAQABABYAAAAEAAQAFwAAAAaABoAbAAAABAAEAC6AQAAFYKI4goAukcAAAAPTKw8u9OTnAc3IbVdeC7HUEEARAB6AHUAYgBhAHMAdABpAGMAVABFAFMAUwBBAEMATABJAEUATgBUAEEARAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAh2diZQVZWyNtXBN5TLlcyAQEAAAAAAAC4BS/wgNHVAbmF5s9VS0E2AAAAAAIAFgBaAFUAQgBBAFMAVABJAEMALQBQAEMAAQAWAFoAVQBCAEEAUwBUAEkAQwAtAFAAQwAEABYAWgB1AGIAYQBzAHQAaQBjAC0AUABDAAMAFgBaAHUAYgBhAHMAdABpAGMALQBQAEMABwAIALgFL/CA0dUBBgAEAAIAAAAIADAAMAAAAAAAAAABAAAAACAAAKMjiVkqRlnu0ueSaQ42oTaN/hFZJBTjaxMkav6CRlpDCgAQAArFl8Ut7ZEp50+JEA8Th+gJACAASABUAFQAUAAvAFoAVQBCAEEAUwBUAEkAQwAtAFAAQwAAAAAAAAAAANWWVY1fJyUNwMwvyFlMffSjEgQQAQAAAIS5m07Az+P3AAAAAA==
System.Security.Cryptography.CryptographicException: ASN1 corrupted data. Expected Application-0; Actual: Constructed ContextSpecific-1
   at System.Security.Cryptography.Asn1.AsnReader.CheckExpectedTag(Asn1Tag tag, Asn1Tag expectedTag, UniversalTagNumber tagNumber) in d:\a\1\s\Kerberos.NET\Asn1\Experimental\AsnReader.cs:line 453
   at System.Security.Cryptography.Asn1.AsnReader.ReadSequence(Asn1Tag expectedTag) in d:\a\1\s\Kerberos.NET\Asn1\Experimental\AsnReader.Sequence.cs:line 58
   at Kerberos.NET.Entities.GssApiToken.Decode(ReadOnlyMemory`1 data) in d:\a\1\s\Kerberos.NET\Entities\GssApi\GssApiToken.cs:line 69
   at Kerberos.NET.MessageParser.Parse(ReadOnlyMemory`1 data) in d:\a\1\s\Kerberos.NET\MessageParser.cs:line 63
   at Kerberos.NET.KerberosValidator.Validate(Byte[] requestBytes) in d:\a\1\s\Kerberos.NET\KerberosValidator.cs:line 50
   at Kerberos.NET.KerberosAuthenticator.Authenticate(Byte[] token) in d:\a\1\s\Kerberos.NET\KerberosAuthenticator.cs:line 48
   at Kerberos.NET.KerberosAuthenticator.Authenticate(String token) in d:\a\1\s\Kerberos.NET\KerberosAuthenticator.cs:line 43`
```

From domain machine I got token:
```
Header: Negotiate oYIB7zCCAeugAwoBAaKCAc4EggHKTlRMTVNTUAADAAAAGAAYAIYAAAAcARwBngAAAAQABABYAAAAEAAQAFwAAAAaABoAbAAAABAAEAC6AQAAFYKI4goAukcAAAAPTKw8u9OTnAc3IbVdeC7HUEEARAB6AHUAYgBhAHMAdABpAGMAVABFAFMAUwBBAEMATABJAEUATgBUAEEARAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAh2diZQVZWyNtXBN5TLlcyAQEAAAAAAAC4BS/wgNHVAbmF5s9VS0E2AAAAAAIAFgBaAFUAQgBBAFMAVABJAEMALQBQAEMAAQAWAFoAVQBCAEEAUwBUAEkAQwAtAFAAQwAEABYAWgB1AGIAYQBzAHQAaQBjAC0AUABDAAMAFgBaAHUAYgBhAHMAdABpAGMALQBQAEMABwAIALgFL/CA0dUBBgAEAAIAAAAIADAAMAAAAAAAAAABAAAAACAAAKMjiVkqRlnu0ueSaQ42oTaN/hFZJBTjaxMkav6CRlpDCgAQAArFl8Ut7ZEp50+JEA8Th+gJACAASABUAFQAUAAvAFoAVQBCAEEAUwBUAEkAQwAtAFAAQwAAAAAAAAAAANWWVY1fJyUNwMwvyFlMffSjEgQQAQAAAIS5m07Az+P3AAAAAA==
```

How I could detect invalid auth? Thank you for help.

**Comment by Zubastic** [comment]
As I found, if token starts with oX - this is SPNEGO container, that could contains kerberos token, or maybe - not. If I try to found `YI` substring in header it would be OK, or not?

**Comment by SteveSyfuhs** [comment]
I'll have to run through with a debugger and see why it's failing with this specifically. The failing token is using NTLM and this library can't handle that, however it should be providing a more explicit "NTLM is not supported" exception.

Your way of checking if it starts with a specific set of characters would work fine. I'll still take a look at why it's not throwing the correct exception.

________________________________

**Comment by Zubastic** [comment]
Thank you.

Old KerbDump version (pre core) throw this exception.
```
[System.IO.InvalidDataException: Unknown NTLM message signature. Actual: 0xSystem.Byte[]; Expected: 0xSystem.Byte[]
   в Kerberos.NET.Entities.NtlmNegotiate..ctor(BinaryReader reader) в C:\Users\Zubastic\Source\Repos\Kerberos.NET\Kerberos.NET\Entities\SpNego\NtlmNegotiate.cs:строка 18](url)
```

And could we add check for NTLM? Something like:
```
                    if (!authenticator.IsNTLMToken(header))
                    {
                        ClaimsIdentity identity = await authenticator.Authenticate(header);
                        context.User = new ClaimsPrincipal(identity);
                        logger.Trace("Successful logged in with kerberos: " + context.User.Identity.Name);
                    }
```

**Comment by SteveSyfuhs** [comment]
Well, mystery solved: the header value is an SPNego response message containing an NTLM message. That isn't even remotely correct as far as any specs I've seen, so I would need to dig into that oddity a little more. The old KerbDump tool is more flexible in what it parses because it doesn't adhere to any specific standard. In any case I've added a specific check and will check this change in later today, and will push an updated nuget package. This is a class already in this library that will let you explicitly check if it's an NTLM message too:

```
bool isNtlm = NtlmMessage.CanReadNtlmMessage(bytes);
```

It will do some inspection of the first and second level of the message, but it won't pick up all scenarios. That's why an explicit exception is through during the attempted decryption pass. The change I reference above will include changes to this method so you can make this check safely.

**Comment by Zubastic** [comment]
Thank you!

**Comment by Zubastic** [comment]
And I think here would be OK to add override with Base64 string like: NtlmMessage.CanReadNtlmMessage(header);

**Comment by Zubastic** [comment]
Well, I created PR, but now I have some problems with lastest code:
```
2020-03-03 01:13:09.9825|ERROR|KerberosMiddleware|Failed to auth with kerberos. Header: Negotiate oXcwdaADCgEBoloEWE5UTE1TU1AAAwAAAAAAAABYAAAAAAAAAFgAAAAAAAAAWAAAAAAAAABYAAAAAAAAAFgAAAAAAAAAWAAAABXCiOIKADk4AAAAD/M0V8KIElG9zAgYCwNDmlijEgQQAQAAAEiR8yPBT2qeAAAAAA==
System.NotSupportedException: NTLM is not supported
   at Kerberos.NET.Entities.SpNego.NtlmContextToken.DecryptApReq(KeyTable keys) in C:\Users\Zubastic\Source\Repos\Kerberos.NET\Kerberos.NET\Entities\SpNego\NtlmContextToken.cs:line 17
   at Kerberos.NET.KerberosValidator.Validate(Byte[] requestBytes) in C:\Users\Zubastic\Source\Repos\Kerberos.NET\Kerberos.NET\KerberosValidator.cs:line 54
   at Kerberos.NET.KerberosAuthenticator.Authenticate(Byte[] token) in C:\Users\Zubastic\Source\Repos\Kerberos.NET\Kerberos.NET\KerberosAuthenticator.cs:line 48
   at Kerberos.NET.KerberosAuthenticator.Authenticate(String token) in C:\Users\Zubastic\Source\Repos\Kerberos.NET\Kerberos.NET\KerberosAuthenticator.cs:line 43
   at KerberosMiddleware.ParseKerberosHeaderAsync(HttpContext context, String header)
```
```
2020-03-03 01:13:12.3393|ERROR|KerberosMiddleware|Failed to auth with kerberos. Header: Negotiate oXcwdaADCgEBoloEWE5UTE1TU1AAAwAAAAAAAABYAAAAAAAAAFgAAAAAAAAAWAAAAAAAAABYAAAAAAAAAFgAAAAAAAAAWAAAABXCiOIKADk4AAAAD+p/mPYPOrW2vSFQEPZSP7ijEgQQAQAAAGkJD6j+5zVAAAAAAA==
System.NotSupportedException: NTLM is not supported
   at Kerberos.NET.Entities.SpNego.NtlmContextToken.DecryptApReq(KeyTable keys) in C:\Users\Zubastic\Source\Repos\Kerberos.NET\Kerberos.NET\Entities\SpNego\NtlmContextToken.cs:line 17
   at Kerberos.NET.KerberosValidator.Validate(Byte[] requestBytes) in C:\Users\Zubastic\Source\Repos\Kerberos.NET\Kerberos.NET\KerberosValidator.cs:line 54
   at Kerberos.NET.KerberosAuthenticator.Authenticate(Byte[] token) in C:\Users\Zubastic\Source\Repos\Kerberos.NET\Kerberos.NET\KerberosAuthenticator.cs:line 48
   at Kerberos.NET.KerberosAuthenticator.Authenticate(String token) in C:\Users\Zubastic\Source\Repos\Kerberos.NET\Kerberos.NET\KerberosAuthenticator.cs:line 43
   at KerberosMiddleware.ParseKerberosHeaderAsync(HttpContext context, String header)
```

```
2020-03-03 01:14:54.2572|ERROR|KerberosMiddleware|Failed to auth with kerberos. Header: Negotiate TlRMTVNTUAADAAAAGAAYAJgAAAAcARwBsAAAABYAFgBYAAAAEAAQAG4AAAAaABoAfgAAABAAEADMAQAAFYKI4goAukcAAAAPW4i7JEnE8k5rDyTbUy10oVoAVQBCAEEAUwBUAEkAQwAtAFAAQwBaAHUAYgBhAHMAdABpAGMAVABFAFMAUwBBAEMATABJAEUATgBUAEEARAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0Gd3OpGShx5ZODvv3TKEZAQEAAAAAAABr1tr13/DVASBzTQPRi50JAAAAAAIAFgBaAFUAQgBBAFMAVABJAEMALQBQAEMAAQAWAFoAVQBCAEEAUwBUAEkAQwAtAFAAQwAEABYAWgB1AGIAYQBzAHQAaQBjAC0AUABDAAMAFgBaAHUAYgBhAHMAdABpAGMALQBQAEMABwAIAGvW2vXf8NUBBgAEAAIAAAAIADAAMAAAAAAAAAAAAAAAADAAAKGzoX0B3ffebANloESj6PWbQt2h/GNauAh3B0ODLDjSCgAQAArFl8Ut7ZEp50+JEA8Th+gJACAASABUAFQAUAAvAFoAVQBCAEEAUwBUAEkAQwAtAFAAQwAAAAAAAAAAAA0vbZbulR4jP6lltHCQWRo=
System.NotSupportedException: NTLM is not supported
   at Kerberos.NET.Entities.SpNego.NtlmContextToken.DecryptApReq(KeyTable keys) in C:\Users\Zubastic\Source\Repos\Kerberos.NET\Kerberos.NET\Entities\SpNego\NtlmContextToken.cs:line 17
   at Kerberos.NET.KerberosValidator.Validate(Byte[] requestBytes) in C:\Users\Zubastic\Source\Repos\Kerberos.NET\Kerberos.NET\KerberosValidator.cs:line 54
   at Kerberos.NET.KerberosAuthenticator.Authenticate(Byte[] token) in C:\Users\Zubastic\Source\Repos\Kerberos.NET\Kerberos.NET\KerberosAuthenticator.cs:line 48
   at Kerberos.NET.KerberosAuthenticator.Authenticate(String token) in C:\Users\Zubastic\Source\Repos\Kerberos.NET\Kerberos.NET\KerberosAuthenticator.cs:line 43
   at KerberosMiddleware.ParseKerberosHeaderAsync(HttpContext context, String header)
```

Code:
```
        #region Private Methods

        private async Task ParseKerberosHeaderAsync(HttpContext context, string header)
        {
            KerberosValidator validator = this.validatorProvider.GetValidator();
            if (validator == null)
            {
                return;
            }

            try
            {
                var authenticator = new KerberosAuthenticator(validator) { UserNameFormat = UserNameFormat.DownLevelLogonName };

                ClaimsIdentity identity = await authenticator.Authenticate(header);

                context.User = new ClaimsPrincipal(identity);
            }
            catch (Exception ex)
            {
                logger.LogException("Failed to auth with kerberos. Header: " + header, ex);
            }
        }

        private static bool CanReadNtlmMessage(string token)
        {
            token = token.Trim();
            if (token.IndexOf(' ') >= 1)
            {
                string[] strArray = token.Split(' ');
                token = strArray[strArray.Length - 1];
            }
            return NtlmMessage.CanReadNtlmMessage(Convert.FromBase64String(token));
        }

        #endregion

        #region Methods

        public async Task Invoke(HttpContext context)
        {
            if (context.Request.Headers.TryGetValue("Authorization", out StringValues authHeader) && authHeader.Count == 1)
            {
                string header = authHeader.First();

                if (CanReadNtlmMessage(header))
                {
                    await this.ParseKerberosHeaderAsync(context, header);
                }
            }

            await this.next(context);
        }

        #endregion
```

And when nuget package will published?

**Comment by SteveSyfuhs** [comment]
The code looks correct. Each of those incoming tickets are genuinely NTLM messages.

Apologies on the nuget front. I have an unrelated bug that I need to fix before it can be updated.

**Comment by Zubastic** [comment]
> The code looks correct. Each of those incoming tickets are genuinely NTLM messages.
But it falls at decryption. I want to decrypt only those tickets, that I could do with keytab file. So I need to check that is not NTLM message and decrypt it?

**Comment by SteveSyfuhs** [comment]
I'm not following. It should fail decryption in all of those cases because they're NTLM. There's nothing the library can do about them at all.

**Comment by Zubastic** [comment]
Hmm, maybe something like this?
```
        private static bool CanRead(string token)
        {
            token = token.Trim();
            if (token.IndexOf(' ') >= 1)
            {
                string[] strArray = token.Split(' ');
                token = strArray[strArray.Length - 1];
            }
            var kerberosRequest = MessageParser.ParseContext(Convert.FromBase64String(token));
            switch (kerberosRequest)
            {
                case NtlmContextToken _:
                case NegoExContextToken _:
                case KerberosUser2UserContextToken _:
                    return false;
                default:
                    return true;
            }
        }
```
Or this shouldn't work?

**Comment by SteveSyfuhs** [comment]
It could certainly work, but then you're always parsing the ticket twice. Why not just let run it through validation and catch the NTLM exception?

**Comment by Zubastic** [comment]
It is just a habit. I don't use try catch for check, if I could avoid it:
https://stackoverflow.com/questions/1308432/do-try-catch-blocks-hurt-performance-when-exceptions-are-not-thrown

**Comment by SteveSyfuhs** [comment]
I guarantee the measurable difference, if any, at scale is negligible in this case. The cost of parsing the ticket twice is an order of magnitude more expensive than the cost of wrapping in a try/catch as well as any cost in unwinding the stack.

**Comment by Zubastic** [comment]
Thank you, I will fix my code.
